### PR TITLE
serbian

### PR DESCRIPTION
**Pull request by Nielqel**
Hello! I created the Serbian language 

upd: sorry, "мех" I forgot to translate to "Krzno"

### CODE REVIEW

**Comment by Nielqel** [comment]
[rs.json](https://github.com/fewfre/TransformiceDressroom/files/15503115/rs.json)

**Comment by Nielqel** [comment]
it was my carelessness with the translation, I'm sorry again! :')

**Comment by fewfre** [comment]
Thanks! I'll update the server with it in a few minutes

**Comment by fewfre** [comment]
Oh! Actually seems I forgot to include a line in all the translation files:
```
"tab_filtering":           { "text":"Filter" }
```

**Pull request merged**
